// Turning a patient record into something the clinician can take away:
// clipboard text, a plain-text report, and a printable HTML report.
import type { PatientData } from '@/lib/patient';

type Toast = (options: { title: string; description: string; variant?: 'destructive' }) => unknown;

// Fallback formatter that alternates Doctor/Patient where AI did not
// return a formatted transcript. Keeps content readable in exports.
export const formatTranscriptWithSpeakers = (transcript: string): string => {
  if (!transcript.trim()) return '';

  // Split transcript into sentences and add alternating speaker labels
  const sentences = transcript.split(/[.!?]+/).filter(s => s.trim());
  let formattedTranscript = '';

  sentences.forEach((sentence, index) => {
    const trimmedSentence = sentence.trim();
    if (trimmedSentence) {
      const speaker = index % 2 === 0 ? 'Doctor' : 'Patient';
      formattedTranscript += `${speaker}: ${trimmedSentence}.\n\n`;
    }
  });

  return formattedTranscript.trim();
};

// The AI transcript when we have one, otherwise the heuristic speaker split.
const transcriptForExport = (patient: PatientData) =>
  patient.formattedTranscript || formatTranscriptWithSpeakers(patient.transcript);

// Utility to copy any string and show a toast confirmation/error
export const copyToClipboard = async (text: string, toast: Toast) => {
  try {
    await navigator.clipboard.writeText(text);
    toast({
      title: "Copied to clipboard",
      description: "Patient information has been copied successfully.",
    });
  } catch (error) {
    toast({
      title: "Copy failed",
      description: "Unable to copy to clipboard.",
      variant: "destructive",
    });
  }
};

// Hand the browser a generated file. The anchor has to be in the document for
// Firefox to honour the click, hence the append/remove dance.
const downloadFile = (filename: string, content: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

// patient-jane_doe-2025-09-27.txt
const exportFileName = (patient: PatientData, extension: string) =>
  `patient-${patient.patientName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}-${new Date(patient.createdAt).toISOString().split('T')[0]}.${extension}`;

// Short summary for the clipboard, from the read-only patient view.
export const buildRecordSummary = (patientData: PatientData) => `Patient: ${patientData.patientName}
Age: ${patientData.age} | Gender: ${patientData.gender}
Date: ${new Date(patientData.createdAt).toLocaleDateString()}

Symptoms: ${patientData.symptoms || 'N/A'}
Medical History: ${patientData.medicalHistory || 'N/A'}
Diagnosis: ${patientData.diagnosis || 'N/A'}
Treatment Plan: ${patientData.treatmentPlan || 'N/A'}

Vitals:
- Blood Pressure: ${patientData.bloodPressure || 'N/A'}
- Heart Rate: ${patientData.heartRate || 'N/A'}
- Temperature: ${patientData.temperature || 'N/A'}
- Respiratory Rate: ${patientData.respiratoryRate || 'N/A'}
- Oxygen Saturation: ${patientData.oxygenSaturation || 'N/A'}
- Weight: ${patientData.weight || 'N/A'}
- Height: ${patientData.height || 'N/A'}`;

// One-line summary used by the note list's Copy button.
export const buildNoteSummary = (note: PatientData) =>
  `Patient: ${note.patientName}\nSymptoms: ${note.symptoms}\nDiagnosis: ${note.diagnosis}\nTreatment: ${note.treatmentPlan}`;

// Full record as text, from the read-only patient view: includes vitals and
// falls back to "N/A" for every empty field.
export const downloadRecordAsText = (patientData: PatientData, toast: Toast) => {
  const content = `PATIENT INFORMATION
====================

Patient Name: ${patientData.patientName}
Age: ${patientData.age}
Gender: ${patientData.gender}
Date: ${new Date(patientData.createdAt).toLocaleDateString()}

VITAL SIGNS
-----------
Blood Pressure: ${patientData.bloodPressure || 'N/A'}
Heart Rate: ${patientData.heartRate || 'N/A'}
Temperature: ${patientData.temperature || 'N/A'}
Respiratory Rate: ${patientData.respiratoryRate || 'N/A'}
Oxygen Saturation: ${patientData.oxygenSaturation || 'N/A'}
Weight: ${patientData.weight || 'N/A'}
Height: ${patientData.height || 'N/A'}

SYMPTOMS / CHIEF COMPLAINT
--------------------------
${patientData.symptoms || 'N/A'}

MEDICAL HISTORY
---------------
${patientData.medicalHistory || 'N/A'}

DIAGNOSIS
---------
${patientData.diagnosis || 'N/A'}

TREATMENT PLAN / NOTES
----------------------
${patientData.treatmentPlan || 'N/A'}

ORIGINAL TRANSCRIPT
-------------------
${transcriptForExport(patientData) || 'N/A'}

Generated by HeyCare Medical Documentation System
`;

  downloadFile(exportFileName(patientData, 'txt'), content, 'text/plain');

  toast({
    title: "Download started",
    description: "Patient notes are being downloaded as text file.",
  });
};

// Note as text, from the notes list: no vitals section, no "N/A" fallbacks.
export const downloadNoteAsText = (note: PatientData, toast: Toast) => {
  const content = `PATIENT INFORMATION
====================

Patient Name: ${note.patientName}
Age: ${note.age}
Gender: ${note.gender}
Date: ${new Date(note.createdAt).toLocaleDateString()}

SYMPTOMS / CHIEF COMPLAINT
--------------------------
${note.symptoms}

MEDICAL HISTORY
---------------
${note.medicalHistory}

DIAGNOSIS
---------
${note.diagnosis}

TREATMENT PLAN / NOTES
----------------------
${note.treatmentPlan}

ORIGINAL TRANSCRIPT
-------------------
${transcriptForExport(note)}

Generated by Medical Conversation Transcriber
`;

  downloadFile(exportFileName(note, 'txt'), content, 'text/plain');

  toast({
    title: "Download started",
    description: "Patient notes are being downloaded as text file.",
  });
};

// Lightweight HTML export that can be printed to PDF
export const downloadNoteAsHtml = (note: PatientData, toast: Toast) => {
  const content = `
<!DOCTYPE html>
<html>
<head>
    <title>Patient Report - ${note.patientName}</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; margin: 40px; }
        .header { border-bottom: 2px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
        .title { color: #2563eb; font-size: 24px; font-weight: bold; }
        .patient-info { background: #f8fafc; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
        .section { margin-bottom: 25px; }
        .section-title { color: #1e293b; font-size: 16px; font-weight: bold; margin-bottom: 10px; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; }
        .content { color: #334155; }
        .transcript { background: #f1f5f9; padding: 15px; border-radius: 6px; font-family: 'Courier New', monospace; font-size: 14px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Medical Patient Report</div>
        <div>Generated on ${new Date().toLocaleDateString()}</div>
    </div>
    
    <div class="patient-info">
        <strong>Patient:</strong> ${note.patientName} &nbsp;&nbsp;
        <strong>Age:</strong> ${note.age} &nbsp;&nbsp;
        <strong>Gender:</strong> ${note.gender} &nbsp;&nbsp;
        <strong>Date:</strong> ${new Date(note.createdAt).toLocaleDateString()}
    </div>

    <div class="section">
        <div class="section-title">Symptoms / Chief Complaint</div>
        <div class="content">${note.symptoms.replace(/\n/g, '<br>')}</div>
    </div>

    <div class="section">
        <div class="section-title">Medical History</div>
        <div class="content">${note.medicalHistory.replace(/\n/g, '<br>')}</div>
    </div>

    <div class="section">
        <div class="section-title">Diagnosis</div>
        <div class="content">${note.diagnosis.replace(/\n/g, '<br>')}</div>
    </div>

    <div class="section">
        <div class="section-title">Treatment Plan / Notes</div>
        <div class="content">${note.treatmentPlan.replace(/\n/g, '<br>')}</div>
    </div>

    <div class="section">
        <div class="section-title">Original Transcript</div>
        <div class="transcript">${transcriptForExport(note).replace(/\n/g, '<br>')}</div>
    </div>
</body>
</html>
    `;

  downloadFile(exportFileName(note, 'html'), content, 'text/html');

  toast({
    title: "Download started",
    description: "Patient notes downloaded as HTML (can be printed to PDF).",
  });
};
